language: ruby
rvm:
- 2.5.0

services:
  - postgresql

before_install:
  - gem update --system
  - gem install bundler
before_script: 
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
script:
  - bundle exec rspec
  - bundle exec rubocop